name: Go CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true  # This handles module caching internally
        cache-dependency-path: go.sum

    - name: Install dependencies
      run: go mod download

    - name: Run Tests
      run: make test
      timeout-minutes: 10  # Added timeout for safety

    - name: Build Application
      run: make build
